[workspace]
members = [
    "roxid-tui",
    "pipeline-service",
    "pipeline-rpc",
    "roxid-cli",
]
resolver = "2"

[workspace.dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = "0.29.0"
