# Multi-Stage Pipeline
# Demonstrates stages with dependencies, conditions, stage-level variables,
# and job-to-job output variable passing.

trigger:
  branches:
    include:
      - main
      - "release/*"
  tags:
    include:
      - "v*"

variables:
  - name: isRelease
    value: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/v')]
  - name: buildConfiguration
    value: Release

stages:
  # ---- Stage 1: Build ----
  - stage: Build
    displayName: Build & Test
    jobs:
      - job: BuildJob
        displayName: Compile Roxid
        pool:
          vmImage: ubuntu-latest
        variables:
          cargoFlags: "--workspace --release"
        steps:
          - checkout: self
            fetchDepth: 0

          - script: echo "Building with flags $(cargoFlags)"
            displayName: Build workspace

          - script: echo "Running tests with flags $(cargoFlags)"
            displayName: Run tests
            env:
              RUST_BACKTRACE: "1"

          - script: |
              VERSION="2.3.0"
              echo "##vso[task.setvariable variable=appVersion;isoutput=true]$VERSION"
            name: getVersion
            displayName: Extract version

      - job: LintJob
        displayName: Lint & Format
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: echo "Checking formatting..."
            displayName: Check formatting

          - script: echo "Running clippy..."
            displayName: Run Clippy

  # ---- Stage 2: Package ----
  - stage: Package
    displayName: Package Artifacts
    dependsOn: Build
    variables:
      appVersion: $[stageDependencies.Build.BuildJob.outputs['getVersion.appVersion']]
    jobs:
      - job: PackageLinux
        displayName: Package Linux binary
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: echo "Building release binary..."
            displayName: Build release binary

          - script: |
              mkdir -p artifact
              echo "roxid-binary-placeholder" > artifact/roxid-linux-amd64
              echo "Packaged roxid v$(appVersion) for Linux"
            displayName: Prepare artifact

          - publish: artifact
            artifact: linux-binary
            displayName: Publish Linux binary

      - job: PackageMac
        displayName: Package macOS binary
        pool:
          vmImage: macos-latest
        steps:
          - script: echo "Building release binary..."
            displayName: Build release binary

          - script: |
              mkdir -p artifact
              echo "roxid-binary-placeholder" > artifact/roxid-darwin-amd64
            displayName: Prepare artifact

          - publish: artifact
            artifact: macos-binary
            displayName: Publish macOS binary

  # ---- Stage 3: Publish ----
  - stage: Publish
    displayName: Publish Release
    dependsOn:
      - Build
      - Package
    condition: and(succeeded(), eq(variables.isRelease, 'true'))
    jobs:
      - job: PublishCrate
        displayName: Publish to crates.io
        pool:
          vmImage: ubuntu-latest
        steps:
          - download: current
            artifact: linux-binary
            displayName: Download Linux artifact

          - script: |
              echo "Publishing Roxid to crates.io..."
              echo "cargo publish -p pipeline-service --dry-run"
              echo "cargo publish -p roxid-tui --dry-run"
              echo "cargo publish -p roxid-cli --dry-run"
            displayName: Publish crates (dry-run)
            env:
              CARGO_REGISTRY_TOKEN: $(cratesIoToken)

  # ---- Stage 4: Notify ----
  - stage: Notify
    displayName: Send Notifications
    dependsOn: Publish
    condition: succeededOrFailed()
    jobs:
      - job: NotifyTeam
        displayName: Notify team
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              if [ "$(Agent.JobStatus)" == "Succeeded" ]; then
                echo "Release succeeded!"
              else
                echo "Release had issues - check pipeline logs"
              fi
            displayName: Send notification
