# Simple Pipeline - Steps Only
# Demonstrates the most basic Azure DevOps pipeline structure:
# triggers, pool, variables, and inline script steps.

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    exclude:
      - "*.md"
      - docs/

pr:
  branches:
    include:
      - main
  autoCancel: true

pool:
  vmImage: ubuntu-latest

variables:
  rustVersion: stable
  CARGO_TERM_COLOR: always

steps:
  - checkout: self
    clean: true
    fetchDepth: 0
    displayName: Checkout repository

  - script: |
      echo "Installing Rust toolchain $(rustVersion)"
      echo "##vso[task.setvariable variable=PATH]$HOME/.cargo/bin:$PATH"
    displayName: Install Rust toolchain

  - script: echo "rustc 1.75.0 && cargo 1.75.0"
    displayName: Display Rust version

  - script: echo "Checking formatting..."
    displayName: Check formatting

  - script: echo "Running clippy lints..."
    displayName: Run Clippy lints
    continueOnError: true

  - script: echo "Building workspace..."
    displayName: Build workspace
    timeoutInMinutes: 15

  - script: echo "Running tests..."
    displayName: Run tests
    env:
      RUST_BACKTRACE: "1"
      RUST_LOG: debug
